site_name: "Top Tech Interview Preparation Guide"
site_description: "A comprehensive resource for interviews at top tech companies."
site_url: "https://metsehafe-eyasu.github.io/interview-prep/"
repo_url: "https://github.com/<your-username>/interview-prep"
repo_name: "interview-prep"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

nav:
  - Home: index.md

  # Consolidate all companies under one top-level "Companies" nav item
  - Companies:
      # - Example:
      #     - Guide: example/guide.md
      #     - Technical:
      #         - Example Technical: example/technical/example-technical-question.md
      #     - System Design:
      #         - Example System Design: example/system-design/example-system-design-question.md
      #     - Behavioral:
      #         - Example Behavioral (Multiple Qs): example/behavioral/example-behavioral-questions.md

      - Bloomberg:
          - Guide: bloomberg/guide.md
          - Technical:
              - Welsh Dictionary Sorting: bloomberg/technical/welsh-dictionary-sorting.md
              - Autocorrect Class: bloomberg/technical/autocorrect-class.md
              - Invalid Transactions: bloomberg/technical/invalid-transactions.md
              - Decode String: bloomberg/technical/decode-string.md
              - Palindrome Number: bloomberg/technical/palindrome-number.md
              - Design Circular Queue: bloomberg/technical/design-circular-queue.md
              - Range Sum Query 2D (Mutable): bloomberg/technical/range-sum-query-2d-mutable.md
          - System Design:
              - Audit system design: bloomberg/system-design/audit-system-design.md
          - Behavioral:
              - Metsehafe Summer 2024: bloomberg/behavioral/metsehafe-summer-2024.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/<your-username>/<repo-name>"
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/<your-profile>/"

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
